apiVersion: apps/v1
kind: Deployment
metadata:
  name: cozystack-api
  namespace: cozy-system
  labels:
    app: cozystack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cozystack-api
  template:
    metadata:
      labels:
        app: cozystack-api
    spec:
      serviceAccountName: cozystack-api
      containers:
      - name: cozystack-api
        image: ghcr.io/kvaps/test:apiserver1@sha256:77fe43d3bd9ad38d4b4f7a7624cf9a3bd991808c886924468cddcdebf2b25abe
