apiVersion: apps/v1
kind: Deployment
metadata:
  name: cozystack-api
  namespace: cozy-system
  labels:
    app: cozystack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cozystack-api
  template:
    metadata:
      labels:
        app: cozystack-api
    spec:
      serviceAccountName: cozystack-api
      containers:
      - name: cozystack-api
        image: ghcr.io/kvaps/test:apiserver1@sha256:f9886d60d3186a9b59433696d11d42038fb40ecfd4479e8a69d7a7bfc6fb65a8
        args: ["--config=/config/config.yaml"]
        volumeMounts:
        - name: config-volume
          mountPath: /config/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: cozystack-api
          items:
          - key: config.yaml
            path: config.yaml
